# Generated by Django 2.0.3 on 2018-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
